### ISSUE TITLE
Installing Linux Version instead of Mac Version on Mac

### ISSUE THREAD

**Issue by Guangyu-Joshua-Feng** [lf-lang/installation#20]
When we run the installation script ( https://install.lf-lang.org/ ) on Mac, it downloads the Linux version instead of the Mac version. The following screenshot is taken from Mac. 
![image](https://github.com/lf-lang/installation/assets/52182553/05e616c6-08f6-4bb1-a5a5-365110ec32f0)

**Comment by lhstrh** [comment]
Can you report what the output of "echo $OSTYPE" is on your machine?

**Comment by Guangyu-Joshua-Feng** [comment]
darwin22.0
